sudo: required
dist: xenial
language: scala
addons:
  apt:
    packages:
    - conntrack
scala:
  - 2.12.8
env:
  - TRAVIS_JDK=adopt@1.8.0-252
  - TRAVIS_JDK=adopt@1.11.0-4

before_install:
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.10.1/install.sh | bash && . ~/.jabba/jabba.sh

install:
  - $JABBA_HOME/bin/jabba install $TRAVIS_JDK && export JAVA_HOME="$JABBA_HOME/jdk/$TRAVIS_JDK" && export PATH="$JAVA_HOME/bin:$PATH" && java -Xmx32m -version

script:
  - ./scripts/setup-minikube-for-linux.sh && ./scripts/test.sh

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.jabba/jdk

before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
